POINTWISE_EVALUATION_PROMPT = """#### GOAL
Your job is to evaluate an instruction-following task carried out by an AI system powered by a large language model.
You will be provided with the input instruction and output of the task by the AI system. Your task is to evaluate the output of the AI system.

#### INPUT
Below are the inputs required for performing the task:
<inputs>
<instruction>
{inputs}
</instruction>
</inputs>

#### OUTPUT
Below is the output of the task by the AI system:
<output>
{outputs}
</output>

## FORMAT FOR THE EVALUATION
- Write the numeric score in 1-9 as output without any additional surrounding text.

Please accurately evaluate the task.
"""

PAIRWISE_EVALUATION_PROMPT = """
# GOAL
Your job is to evaluate a task carried out by two AI systems powered by large language models.
You will be provided with the inputs and outputs of the two AI systems. Your task is to evaluate which response is better.
# INPUT/s
Below are the inputs required for performing the task:
<inputs>
<customer_query>
{inputs}
</customer_query>
</inputs>

# OUTPUT A
Below is the output of the first AI system:
<output_a>
{outputs_a}
</output_a>

# OUTPUT B
Below is the output of the second AI system:
<output_b>
{outputs_b}
</output_b>

## FORMAT FOR THE EVALUATION
- Write which response is better (i.e. A or B) without any additional surrounding text.

Please accurately evaluate the task.
"""

REWRITE_PROMPT = """### Goal
You are an expert at paraphrasing. Below is a text paragraph generated by an AI system. Rewrite the text paragraph in your own words.
You should keep the original meaning of the text paragraph without adding any additional information or lose any important details. 
But you should also make the text paragraph in your own words.

### Original Paragraph:
{original_response}

### Rewritten Paragraph:
"""

# self identity
SELF_RECOGNITION_PROMPT = """Below is a text paragraph of a user's query. Determine whether the paragraph is generated by you or not. You should only answer Yes or No.

### Paragraph:
{original_response}

### Response:
"""

SUMMARY_PROMPT = """You are a news-article summarizer. Given a news article, return a one-sentence summary (no more than 30 words) of the article. Return only the one-sentence summary with no other text.

#### Article:
{article}

#### Summary:
"""

